<!DOCTYPE html:html [
<!ENTITY ent1 'foo'>
<!ENTITY ent2 'foo<br/>'>
<!ELEMENT html:html (html:head, html:body)>
<!ATTLIST html:html xmlns:html CDATA #IMPLIED>
<!ELEMENT html:head (html:title)>
<!ELEMENT html:title (#PCDATA)>
<!ELEMENT html:body (html:p)>
<!ELEMENT html:p (#PCDATA|html:br)*>
<!ATTLIST html:p class CDATA #IMPLIED>
<!ELEMENT html:br EMPTY>
]>
<html:html xmlns:html='http://www.w3.org/1999/xhtml'>
<html:head>
<html:title>test file</html:title>
</html:head>
<html:body> 
<html:p class="visible:false">bar</html:p>
</html:body>
</html:html>
