<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html [
<!ENTITY ent1 SYSTEM 'external_foo.ent'>
<!ENTITY ent2 SYSTEM 'external_foobr.ent'>
<!ENTITY ent5 PUBLIC "entityURI" "entityFile" NDATA notation1>
<!ELEMENT html (head, body)>
<!ATTLIST html xmlns CDATA #IMPLIED>
<!ELEMENT head (title)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT body (p)>
<!ELEMENT p (#PCDATA|br)*>
<!ELEMENT br EMPTY>
<!NOTATION notation1 PUBLIC "notation1File">
]>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<title>external entity encoding sample</title>
</head>
<body> 
<p>bar&ent2;&ent1;</p>
</body>
</html>
